import React, { useState } from "react";

export default function DJNishant() {
  const [searchTerm, setSearchTerm] = useState("");
  const [loadedSong, setLoadedSong] = useState(null);

  const handleSearch = () => {
    alert(`Search for: ${searchTerm}`);
  };

  const handleLoadSong = () => {
    setLoadedSong("https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3");
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-purple-900 via-black to-purple-900 text-white p-6">
      <h1 className="text-5xl font-bold text-center mb-6 font-mono tracking-widest">Madness Audio</h1>

      <div className="max-w-lg mx-auto bg-white/10 p-6 rounded-2xl shadow-xl space-y-4">
        <input
          type="text"
          placeholder="Search for a song..."
          value={searchTerm}
          onChange={(e) => setSearchTerm(e.target.value)}
          className="w-full px-4 py-2 rounded-lg bg-white/20 text-white placeholder-gray-300 focus:outline-none"
        />
        <button
          onClick={handleSearch}
          className="w-full py-2 bg-purple-600 hover:bg-purple-700 rounded-lg font-semibold transition"
        >
          Search
        </button>
      </div>

      <div className="text-center mt-8">
        <button
          onClick={handleLoadSong}
          className="px-6 py-3 bg-pink-600 hover:bg-pink-700 rounded-xl font-bold shadow-lg transition"
        >
          Load Sample Song
        </button>
      </div>

      {loadedSong && (
        <div className="flex justify-center mt-10">
          <div className="w-full max-w-md bg-white/10 p-4 rounded-2xl shadow-lg">
            <h2 className="text-xl font-semibold mb-2">Now Playing</h2>
            <audio controls src={loadedSong} className="w-full rounded-lg" />
          </div>
        </div>
      )}

      <footer className="text-center mt-16 text-sm text-gray-400">
        &copy; 2025 Madness Audio | Feel the beat, live the madness.
      </footer>
    </div>
  );
}
